Reborn
Bopzor/movies-list pull request #5
Opened 2018-05-02 14:09 UTC by Bopzor

What needs to be changed before merging reborn into master?

2018-05-04 08:13 UTC, nilscox commented on api/index.js
> +api.use((req, res, next) => {
This can be discarded.

2018-05-11 19:16 UTC, nilscox requested changes
Great work! Don't forget to change the favicon ;)

2018-05-11 19:16 UTC, nilscox commented on api/index.js
> +api.use((req, res, next) => {
This can be discarded.

2018-05-11 19:16 UTC, nilscox commented on wat-wat.sublime-project
> +{
This file should not be tracked by git.

2018-05-11 19:16 UTC, nilscox commented on web/.eslintrc.json
> +{
Review indentation in the whole file. Plus missing new line at the end of the file.

2018-05-11 19:16 UTC, nilscox commented on web/.gitignore
> +yarn-error.log*
Missing new line.

2018-05-11 19:16 UTC, nilscox commented on web/public/manifest.json
> +{
Find out what's this file for and set correct values for wat-wat.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.css
> +}
Missing new line.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +        <h1 className='page-title'>Whatcha Watchin?</h1>
Wrap title and subtitle in a `div` with some padding instead of having `margin-top` and `margin-bottom` for `h1` and `h3`

2018-05-11 19:16 UTC, nilscox commented on web/src/App.css
> +  align-self: center;
No need for `align-self`, `text-align: center` should do.

2018-05-11 19:16 UTC, nilscox commented on web/package.json
> +    "eject": "react-scripts eject"
Add a `lint` script.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +    this.state = {
Default `state` can be defined as a class property.

```js
class App extends Component {
  state = {
    // ...
  };
}
```

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +    this.state = {
(the constructor is not necessary then)

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +  render() {
- Try to have *only one* `this.state` in this function.

- `MuiThemeProvider` should wrap the entire app. You can set it when exporting the app instead of here, in the render method of your App. Something like:
```js
export default (props) => <MuiThemeProvider theme={theme}><App {...props} /></MuiThemeProvider>;
```

- No need for the loadingTitle variable. You can render the loader conditionnally in the `return` with `{ this.state.loadingTitle && <LinearProgress ... /> }`

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +        this.setState({
Trailling whitespace.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +        this.setState({
There is also an issue with the indentation...

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +
Extra new line.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +  handleSubmitTitle(title) {
- 56: Extra comma, and missing semicolon. Also, a new line after this.setState could be nice.
- 59: `!movie` instead of `movie === null` would be less explicit, but could be better for readability. But maybe not. Both options are valid. Make your choice.
- 60: The call to `setState` for `loadingTitle` can be done in a `.then` after the `.catch`. Extra coma also...
- 61: Missing semicolon.
- 77: Missing semicolon.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +    const isSeen = this.state.filter.notSeen;
`isSeen` is a pretty confusing name for this variable... Beware of ~~pickpockets~~ copy/paste!

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +    if (movie.id === this.state.displayMovieId) {
Can be done without a if (with a ternary). Less readable, but more concise. Your call :telephone_receiver:.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +  handleSendSortPlaces(places) {
Maybe a better name for this method can be found...

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +      .then(movies => {
No need for the `{}` as it's a one-line function.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +    setMovieSeen(movie, changedSeen)
Missing return (not needed, but for consistensy with the other methods).

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +        const movieIdx = movies.findIndex(m => m.id === movie.id);
`movies.findIndex` is often used in this file. It could be factorized as a class method (`this.findMovieIndex(movie)`).

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +        const movies = this.state.movies.slice();
This function is hard to read / understand, but this is the best you can do regarding immutability for now. We'll probably try something easier to use than `slice`, `splice`, `findIndex` and all that crap (after the merge of this PR).

2018-05-11 19:16 UTC, nilscox commented on web/src/index.css
> +  margin: 0;
`margin` and `padding` are already set to `0` in `reset.css`. I wouldn't mind to see `font-family: sans-serif` directly inline in the `<body>` tag. (also, the font-family may be overriden by material-ui, and thus this one may not have any effect at all).

2018-05-11 19:16 UTC, nilscox commented on .gitignore
> +*.sublime-project
`*.sublime-*` would also work.

2018-05-11 19:16 UTC, nilscox commented on web/public/index.html
> +    <!--
Remove unneded comments.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +import {
You could also `import * as actions from './...';`, and will call the functions with `action.getMoviesList()`.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.css
> +  height: 85%;
`flex: 1` is more appropriate I think.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.css
> +  flex: 1;
The `flex: 1` corresponding to the right side is in another file, which can lead to headaches when looking for the flex structure of the document. If you feel ok with this for now, it's fine, but keep it in mind...

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> + * Requests to Wat-Wat API:
Add documentation for the `Movie`, `Comment` and `searchedMovie` types.

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +const API_URL = BASE_URL + BASE_API_URL;
Template string!

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +const OMDB_API_URL = 'http://www.omdbapi.com/?apikey=8ce98bc8';
Find a way to extract the key from git (environment variables is a very common solution).

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +  console.log(url, opts);
Remove debug logs.

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +      return promise;
As you don't return `promise.then(...)`, you don't need a variable. You can directly return `res.json()` or `res.text()`.

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +  }),
Fail indent.

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +  const url = API_URL + '/' + movie.id
Use a template string.

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +      seen: seen,
You could remove the `: seen`.

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +      }))
Missing semicolon.

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> +export {
You could also use the `export function getMovies() { ... }` syntaxe when declaring each function. This way you don't need to list all the functions here.

2018-05-11 19:16 UTC, nilscox commented on web/src/actionsToApis.js
> + *  title: string,
Fail indent.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.js
> +const SortableItem = SortableElement(props => {
Create a real class for the movie item and the movies list, like `MovieItem`. Then you can create the higher order component `SortableMovieItem` by declaring a `const` with value the call to SortableElement.
This would be better for readability.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.js
> +  const movies = props.movies;
You can fetch specific attributes in the `props` object with the [http://putaindecode.io/fr/articles/js/es2015/destructuring/](destructuring syntaxe) from es6. You can then also use it for the `onTitleClick` and `removeMovie` callbacks.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.js
> +    this.state = { movies: this.props.movies };
You don't need to set the value for the `movies` state variable. It will be automatically set by `getDerivedStateFromProps` right after the call to the constructor.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.js
> +  onSortEnd = ({oldIndex, newIndex}) => {
Missing spaces between the `{}` of the destructuring syntaxe.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.js
> +    for (let i = 0; i < newMoviesOrder.length; i++)
Nice! Try to do it with reduce as an exercise if you want!

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.js
> +    )
Missing semi.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.css
> +.list {
Mixed tabs and spaces in indentation.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.css
> +	align-items: center;
Items (the children of this container) are defined with a `flex` value, thus they are supposed to be flexible and take as much space as possible in the container. The align-items is irrelevent in this context.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.css
> +  pointer-events: auto !important;
Maybe something with `:focus` is possible instead of using `!important`. I don't really know actually... but you can give it a try.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MoviesList/MoviesList.css
> +	flex: 2;
Why 2?

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MovieDetails/MovieDetails.js
> +      return <div className='movie-details' />;
You can return `null` here. The `flex` attribute should be on the outer div (that this component isn't aware of).

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +          <MovieDetails
Here, `MovieDetails` set itself as `flex: 1`, which means that it knows it is inside a `flex container`. It then can't work by itself. A better solution would be to make `MovieDetails` agnostic of all context. This simply means that the `flex: 1` attribute should be the responsability of the App.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MovieDetails/MovieDetails.css
> +	flex: 1;
This should be in `App.js` (see the comment on `MovieDetails.css`).

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MovieDetailsBlockInfos/MovieDetailsBlockInfos.css
> +.movie-details-title {
You could remove the `movie-details` prefix, and have the whole details black encapsulated and prefix thoses classes with `.movie-details .block-infos`.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MovieDetailsBlockInfos/MovieDetailsBlockInfos.css
> +	display: flex;
Maybe you don't need a flex container here.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/MovieDetailsBlockInfos/MovieDetailsBlockInfos.css
> +.movie-details-block-infos {
The `seen` button can also be in `display: absolute; top: 5px; right: 5px;`, this would allow you to remove the flex container `-with-seen-button`...

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/IconsButton/IconsButton.js
> +const theme = createMuiTheme({
Declare the `theme` constant in a separate file that you can also include in `App.js` and `SimpleIcons.js`.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/SimpleIcons/SimpleIcons.js
> +const theme = createMuiTheme({
Declare the `theme` constant in a separate file that you can also include in `App.js` and `IconsButton.js`.

2018-05-11 19:16 UTC, nilscox commented on web/src/App.js
> +const theme = createMuiTheme({
Declare the `theme` constant in a separate file that you can also include in `IconsButton.js` and `SimpleIcons.js`.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/IconsButton/IconsButton.js
> +const RemoveIconButton = (props) => {
A bit of refactor can be done there! All your buttons have the same structure, which means that you can create a *generic* button component, with its props being the values that change from one button to another (`className`, `onClick`, ...).

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/AddMovieInput/AddMovieInput.js
> +          <form className='form-add-movie-title' onSubmit={onSubmit}>
Fail indent.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/AddMovieInput/AddMovieInput.js
> +        <div className='input-and-filters'>
Weird! The input is not inside this `div` :D 
It seems you don't really need this `div` actually.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/AddMovieInput/AddMovieInput.js
> +      this.setState({ title: suggestion.title})
Space.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/AddMovieInput/AddMovieInput.js
> +      }, 500);
Extract the magic value to a constant at the begining of the file (after the imports)

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/AddMovieInput/AddMovieInput.js
> +const renderSuggestionsContainer = (highlighted, { containerProps , children }) => {
Call it `poster` or `highlighted_poster` instead of just `highlighted`, as it may lead to confusion with the `highlighted` state attribute of the `AddMovieInput` component, which is an object (and the one in this function is just a string of the poster's URL).

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/AddMovieInput/AddMovieInput.css
> +  flex-direction: row;
There are 2 flex containers in `flex-direction: row` one inside the other. (see the comment on `AddMovieInput.js`).

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.js
> +  createMovieComment(comment) {
Another way of separating the code for a single `MovieComment` would be to declare another react component (possibly inside this file).

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentInput/CommentInput.css
> +	display: flex;
A flex container may not be necessary here.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentInput/CommentInput.css
> +.full-comment-input {
This works fine. I would have put a `comment-input-wrapper` instead of a `full-comment-input`, but this works. The best naming is always the one you remember.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentInput/CommentInput.js
> +            id="author-name"
Why an id?

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.css
> +	justify-content: space-between;
You use `flex-direction` with a child having a `flex: 1` value, which means that this container's childrens will take as much place as possible to fit in the container's width. It that case, the `justify-contents` property is irrelevent.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.css
> +	display: flex;
I guess a flex container can be avoided.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.css
> +	display: flex;
Same here, no need for a flex container.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.css
> +	height: 310px;
A fixed height will make the container scroll even if it is not at full height (see screenshot). Sure you want this?
![screenshot from 2018-05-11 21-08-54](https://user-images.githubusercontent.com/5544363/39942358-8c217a48-555f-11e8-967e-2f2d42260cbe.png)

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.js
> +import React, { Component } from 'react';
The comments order is not always the same! You can [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort](sort) them by creation date for example.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.js
> +import React, { Component } from 'react';
Also, adding the creation date would be nice! (like pretty small on the top right corner, in color `#CCC`, and with a tooltip showing the last update date on hover :p)

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.js
> +      this.setState({
Fail indent.

2018-05-11 19:16 UTC, nilscox commented on web/src/Components/CommentsZone/CommentsZone.js
> +      newComment: '',
Missing semi.

2018-05-12 11:00 UTC, Bopzor commented on wat-wat.sublime-project
> +{
482ba22

2018-05-12 11:10 UTC, Bopzor commented on .gitignore
> +*.sublime-project
5d4256a

2018-05-12 13:39 UTC, Bopzor commented on web/src/App.js
> +import {
4b7ea5f

2018-05-12 13:52 UTC, Bopzor commented on web/src/App.js
> +const theme = createMuiTheme({
aedb67f

2018-05-21 16:06 UTC, Bopzor commented
Merge reborn in master with git

2018-05-21 16:06 UTC, closed without merging